#!/usr/bin/env python3
"""Build static Run 0 review dashboard from jsonl artifacts."""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ARTIFACT_DIR = SCRIPT_DIR.parent
PREDICTIONS_PATH = ARTIFACT_DIR / "raw_predictions.jsonl"
PROMPTS_PATH = ARTIFACT_DIR / "prompt_inputs.jsonl"
DATA_JS_PATH = SCRIPT_DIR / "data.js"


def load_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open(encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_no}: invalid JSON") from exc
    return rows


def build_dataset() -> dict:
    prompts_by_id: dict[str, dict] = {}
    prompt_order: list[str] = []

    for row in load_jsonl(PROMPTS_PATH):
        pid = row["prompt_id"]
        prompt_order.append(pid)
        prompts_by_id[pid] = {
            "prompt_id": pid,
            "problem": row.get("problem", ""),
            "gold_answer": str(row.get("gold_answer", "")),
            "rollouts": [],
        }

    rollouts_by_prompt: dict[str, list[dict]] = defaultdict(list)
    for row in load_jsonl(PREDICTIONS_PATH):
        pid = row["prompt_id"]
        completion = row.get("completion", "") or ""
        rollouts_by_prompt[pid].append(
            {
                "parsed_answer": str(row.get("parsed_answer", "")),
                "correct": bool(row.get("correct", False)),
                "cluster_id": row.get("cluster_id"),
                "completion": completion,
                "char_count": len(completion),
            }
        )

    prompts_out: list[dict] = []
    for index, pid in enumerate(prompt_order):
        base = prompts_by_id[pid]
        rollouts = rollouts_by_prompt.get(pid, [])
        if len(rollouts) != 8:
            print(
                f"warning: prompt {pid} has {len(rollouts)} rollouts (expected 8)",
                file=sys.stderr,
            )
        n_correct = sum(1 for r in rollouts if r["correct"])
        cluster_ids = {r["cluster_id"] for r in rollouts}
        prompts_out.append(
            {
                "index": index,
                "prompt_id": pid,
                "problem": base["problem"],
                "gold_answer": base["gold_answer"],
                "n_correct": n_correct,
                "n_rollouts": len(rollouts),
                "n_clusters": len(cluster_ids),
                "rollouts": rollouts,
            }
        )

    return {"prompt_count": len(prompts_out), "prompts": prompts_out}


def write_data_js(dataset: dict) -> None:
    payload = json.dumps(dataset, ensure_ascii=False, separators=(",", ":"))
    DATA_JS_PATH.write_text(
        f"/* Generated by build_review_dashboard.py — do not edit */\n"
        f"window.REVIEW_DATA = {payload};\n",
        encoding="utf-8",
    )


def main() -> int:
    if not PREDICTIONS_PATH.is_file():
        print(f"error: missing {PREDICTIONS_PATH}", file=sys.stderr)
        return 1
    if not PROMPTS_PATH.is_file():
        print(f"error: missing {PROMPTS_PATH}", file=sys.stderr)
        return 1

    dataset = build_dataset()
    write_data_js(dataset)
    size_mb = DATA_JS_PATH.stat().st_size / (1024 * 1024)
    print(f"wrote {DATA_JS_PATH} ({dataset['prompt_count']} prompts, {size_mb:.2f} MB)")
    print("open index.html in a browser (see README.md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
